# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    name: Test on JDK ${{ matrix.java-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java-version: [ '8', '11', '17' ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    # Checkout the repo
    - uses: actions/checkout@v3
    
    # Set up JDK 8, 11, or 17
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    
    # Build with Gradle on Ubuntu, Windows, or macOS
    - name: Build with Gradle on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sh ./gradlew build -Prelease
    
    - name: Build with Gradle on Windows
      if: matrix.os == 'windows-latest'
      run: .\gradlew build -Prelease
    
    - name: Build with Gradle on macOS
      if: matrix.os == 'macOS-latest'
      run: sh ./gradlew build -Prelease
